### PR TITLE
check_functions: Recycle the argument's name if argName is not specified

### LINKED ISSUE #140: check_functions should throw informative errors even if argName is not given
As discussed directly, the `check_functions` (e.g. `check_logicalArgument()`) are, on the one hand, called without an `argName` (but just with the `arg`), but, on the other hand, require this argument if they throw errors. Therefore, they fail with an error from `stop()` rather throwing an informative error.
``` r
library(eatGADS)
somearg <- TRUE
eatGADS:::check_logicalArgument(somearg)
#> NULL
anotherarg <- 1
eatGADS:::check_logicalArgument(anotherarg)
#> Error in eatGADS:::check_logicalArgument(anotherarg): Argument "argName" fehlt (ohne Standardwert)
```

<sup>Created on 2025-09-25 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

### PR DESCRIPTION
**Pull request by weigtnik**
Closes #140 by enabling the mini checks to recycle `arg` if `argName` is missing. In cases where these functions were used with minor errors, these are corrected throughout the package. Additionally, `check_single_varName` is being removed and `check_characterArgument` is used in its stead.

Not an urgent PR.

Going forward, I wondered whether it would make sense to further standardize some of the mini checks that are being performed at multiple points in the package, e.g., checking if an argument is a numeric or character vector of exactly length x or at least length y.

### CODE REVIEW

File: tests/testthat/test_check_functions.R [hunk 1]
```diff
@@ -57,3 +48,11 @@ test_that("check_numericArgument", {
                "'test' needs to be a numeric vector of length 1.")
   expect_silent(check_numericArgument(1, "test"))
 })
+
+test_that("Argument name is recycled if no argName is provided", {
```
Comment (beckerbenj) [inline tests/testthat/test_check_functions.R]: Why is `expect_match()` being used instead of `expect_error()`?

**Review by beckerbenj — COMMENTED** [review]
Looks very good to me, thanks for taking care of this (only one minor comment below)!

> Going forward, I wondered whether it would make sense to further standardize some of the mini checks that are being performed at multiple points in the package, e.g., checking if an argument is a numeric or character vector of exactly length x or at least length y.

I agree, input validation could be improved throughout the package. This also could be something for a student research assistant.

File: tests/testthat/test_check_functions.R (hunk 1 above)
Comment (weigtnik) [reply tests/testthat/test_check_functions.R:52]: My reasoning was that, in this specific test, I don't care that much about the _exact_ message or that an error is thrown, but rather that the error message includes "somearg". Therefore, this test would not fail if the structure of the message were adjusted for reasons unrelated to what I want to test here. Does that make sense?
